stages:
  - dockerize
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  BRANCH: $CI_COMMIT_REF_NAME

dockerize:
  image: docker:latest
  stage: dockerize
  services:
    - docker:dind
  script:
    - docker build --build-arg BRANCH=$BRANCH -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
    - echo $TAG_COMMIT
  only:
    - develop
    - main


deploy-beta:
  image: alpine:latest
  stage: deploy
  tags:
    - gitlab-org
  script:
    - apk update && apk add openssh-client
    - chmod og= $ID_RSA

    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f beta-dashboard || true"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 3003:80 --name beta-dashboard $TAG_COMMIT"
  only:
    - develop

